CREATE DATABASE store;
USE store;
CREATE TABLE inventory (
	ID INTEGER(11) AUTO_INCREMENT NOT NULL,
    Product Name VARCHAR(30) NOT NULL,
    Type VARCHAR(30) NOT NULL,
    Price DECIMAL(30, 2) NOT NULL,
    Quantity INTEGER(30) NOT NULL,
    PRIMARY KEY (ID)
);